### ISSUE TITLE
[image] add the ability to use picture syntax

### ISSUE THREAD

**Issue by jescowuester** [storyofams/next-boilerplate#1]
**Is your feature request related to a problem? Please describe.**

Images are the heaviest part of a website. Lazyloading is rather hard to implement and the picture/srcset syntax is all over the place and confusing for new devs. Webp is an amazing solution for this but its barely used because it's not yet stable in every browser.

Taking care of this issue would greatly improve web accessibility for people on slow networks.

**Describe the solution you'd like**

An improvement to the Image component that would address all of these issues, similar to gatsby-images.
Users would still need to convert and provide the images themselves but 
 - lazyloading
 - webp fallbacks 
 - responsive sizes
are made easy.

A nice and flexible api could look like this:

```
<Image
	loading='lazy' // default behavior
    placeholder='img-xxs.jpg' // blured version of this is gonna be shown while the image loads
	src='img-md.jpg' // the default source and fallback
    sizes={['/img-sm.jpg', '/img-md.jpg','/img-lg.jpg']} // responsive array like styled-system that can take multiple sources
	webp={['/img-sm.webp', '/img-md.webp','/img-lg.webp']}
/>
```
Most keys are optional so sth like this is possible
```
<Image src='img-md.jpg' webp='img-md.webp' />
```

This integrates well with pretty much every common image optimization service like Cloudinary that provide flexible links for every size.

**Additional context**
Made a demo here https://codesandbox.io/s/optimized-image-sf8ku

**Comment by MrBamBam** [comment]
👏  for webP 🤓 

I think this would be a very nice approach for handling all the annoying stuff that come along
I do have some questions regarding the implementation you described. 

Are we going to handle the "blurring" of the initial loaded image or is this handled by the user/server providing a fallback image (or both? 😛) ?

Is there a specific reason you choose to go the route of adding the source image (for the default size) as src ?

Another approach could be;
```
<Image 
	loading='lazy' // default behavior
    placeholder='img-xxs.jpg' // blured version of this is gonna be shown while the image loads
    defaultSize="md" // optional with a fallback if not supplied
    sizes={['/img-sm.jpg', '/img-md.jpg','/img-lg.jpg']} // responsive array like styled-system that can take multiple sources
	webp={['/img-sm.webp', '/img-md.webp','/img-lg.webp']}
/>
```

With this approach you omit the (default) src value and I feel it's a little bit more self explainatory.  But I can also see it being a little bit more messy in the Image component itself.

What are your thoughts on this?

**Comment by jescowuester** [comment]
blurring is going to be handled by imagesharp, its a fairly common way to create lqip's. Css blur also blurs the edges which looks pretty bad. 

If no image is specified/ the picture syntax isn't supported src is used. `defaultSize` is a bit inflexible, what if you only have 1 webp fallback? Or no responsive images at all? 
```
<Image defaultSize='sm?' sizes={['/img-md.jpg']} />
vs
<Image src='img-md.jpg' />
```

**Comment by MrBamBam** [comment]
https://nextjs.org/blog/next-10#nextjs-image-component
