### ISSUE TITLE
[rfc] move from styled-components to emotion

### ISSUE THREAD

**Issue by jescowuester** [storyofams/next-boilerplate#13]
Both libraries have the exact same API but emotion has a few notable advantages:

**Advantages**
 - better typescript support
 - smaller bundle size
 - can exclude properties from dom (no more `React does not recognize the ... prop on a DOM element.`)
 - better integration with styled-system and its ecosystem (chakra)
 - should be able to handle circular dependencies (fixes #4)

**to consider**
 - the learning curve for emotion is a bit higher since its made out of multiple packages but the end api is essentially identical to styled-components
 - older projects will still depend on styled-components introducing some inconsistencies

**Comment by awilderink** [comment]
Totally in! Learning curve is not really a thing to consider, it's pretty straightforward.

**Comment by leeuwis** [comment]
Same, learning curve does not really matter if it's better. It's always going to be the case with older projects, shouldn't stop us from using something that considerable better.

However, `styled-components` community seems to be quite a bit bigger and is growing faster at the moment compared to `emotion`:
https://www.npmtrends.com/styled-components-vs-emotion

**Comment by jescowuester** [comment]
@leeuwis https://www.npmtrends.com/styled-components-vs-@emotion/core emotions actually gets more downloads, also because most libraries that use css-in-js use emotion

**Comment by MrBamBam** [comment]
I don't really care which library we use. I was using emotion before I used styled-components and I beleive there isn't much of learning curve. But like you mentioned it does solve quite some issues, so might be worth the switch.

@jescowuester didn't you say btw that you'd prefer the classname based syntax over styled-system syntax ?

**Comment by jescowuester** [comment]
@MrBamBam className syntax (in the context of tailwindcss) is nicer IMO but lacks flexibility. One-off styles can quickly become disorganized and are harder to maintain.

**Comment by BJvdA** [comment]
How does `styled-components` v5 compare to `emotion` bundlesize and performance?

Apparently [this](https://github.com/styled-components/styled-components/pull/3006) is going to fix the HTML prop problems, however after 4 years of this issue it still isn't released and only now merged...

**Comment by jescowuester** [comment]
bundlesize and performance for both is close to identical after v5. One huge issue is that the `as` prop doesn't work with typescript in emotion so `<Text as='a' href='#'>` will throw a type error (`href doesn't exist on text`).

**Comment by jescowuester** [comment]
closing this for now because of the issue above
