### ISSUE TITLE
[rfc] move from axios to fetch + polyfill

### ISSUE THREAD

**Issue by jescowuester** [storyofams/next-boilerplate#15]
## why
 - fetch can do anything Axios can
 - fetch is a browser standard
 - can be polyfilled via [unfetch](https://www.npmjs.com/package/isomorphic-unfetch) (500b instead of 4.4kb gziped)

**Comment by MrBamBam** [comment]
I'm very much down for this :) 

I would also like to opt for SWR as well!

**Comment by jescowuester** [comment]
SWR is already in there, maybe we should add some examples of when/how to use it?

**Comment by BJvdA** [comment]
only remark I have  is polyfilling for [abortcontroller](https://github.com/developit/unfetch/issues/54) but it's an edge case

I have used the CancelToken in axios before for example in search components
