### ISSUE TITLE
[ISystem] add the ability to extend html types

### ISSUE THREAD

**Issue by jescowuester** [storyofams/next-boilerplate#2]
**Is your feature request related to a problem? Please describe.**

Extending a type of `React.HTMLAttributes<HTMLInputElement>` leads to conflicting props right now.

**Describe the solution you'd like**
you can extract
```
extends ISystem,
    Omit<Omit<React.HTMLAttributes<HTMLInputElement>, 'color'>, 'css'>
```
into its own interface that can be used like
```
extends ISystem<HTMLInputElement>
```
To do that we need to find all conflicting props and test if this interface works with all components

**Describe alternatives you've considered**
always use the Omit helper which gives more flexibility but gets annoying quickly

**Comment by MrBamBam** [comment]
Might be best if we add a pre-commit hook with a test script to check for conflicting props and then add them to the interface if needed ? 

Or would you prefer some kind of catch all solution that doesn't require any additional effort once there?

**Comment by jescowuester** [comment]
no, just use it in parfum.nl and see if there are any other conflicts besides color and css
