### ISSUE TITLE
[setup] add authentication wrapper component

### ISSUE THREAD

**Issue by jescowuester** [storyofams/next-boilerplate#3]
**Is your feature request related to a problem? Please describe.**

Authentication with nextjs and fetching data from protected routes is currently a pain. Need to figure out the best way to do this and if possible abstract it away.

**Comment by MrBamBam** [comment]
Are you thinking about a util that you can add to the getInitialProps to check for cookies and res.writehead(301) if need not authenticated?

**Comment by jescowuester** [comment]
yes but it should also help fetching data that requires headers since those need to be included manually in all server requests

**Comment by MrBamBam** [comment]
https://github.com/zeit/next.js/pull/10973

Just posting this for reference.

I do think that the session storing might be a little too much to put in the boilerplate as I think we're going to have to come up with a common solution for the CSRF cookies from the backend. And if you need something different then that you're already looking at a more custom implementation than just the cookies I think. 

Once I have a full example with the CSRF cookies I'll make a pull request to see if it would fit the boilerplate.

**Comment by MrBamBam** [comment]
Closing for now as we're going to provide those examples in a more `create-next-app` fashion :)
