### ISSUE TITLE
remove duplicate ThemeProvider

### ISSUE THREAD

**Issue by awilderink** [storyofams/next-boilerplate#54]
The Theme provider is currently implemented in the `_app.tsx` page and also in `components/Providers`. Maybe we should choose.

**Comment by MrBamBam** [comment]
I saw this yesterday as well. I still like the API of the Provider component (as this also makes it easier to re-use). So switching to the Provider component would make the most sense te me.

**Comment by awilderink** [comment]
I would also day to move all providers to `components/Providers`
