### ISSUE TITLE
the useId hook does not work at all

### ISSUE THREAD

**Issue by awilderink** [storyofams/next-boilerplate#58]
**Describe the bug**
The useId hook does not work 

**To Reproduce**
1. use the useId hook by for example creating a from with two input fields (`src/components/common/Input`)
2. the console will warn you you have two duplicate ids

**Expected behavior**
An incrementing id. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Chrome
 - Version: 87.0.4280.141 (Officiële build) (x86_64)

**Additional context**
Simplifying the 'hook '(it will not be a hook anymore after this change), will solve the issue: 
```typescript
// src/hooks/useId.ts

let _id = 0;
const genId = () => ++_id;

export default function useId(): number {
  return genId();
}
```

**Comment by MrBamBam** [comment]
I'm aware of the issue as the ID is currently hardcoded (when not specified as one of the props).

Reason being is that the above fucntion (or the hook that was previously there) can cause for different IDs being generated between the client and server (more info and explanation can be found [here](https://github.com/radix-ui/primitives/issues/331).

I was thinking of implementing a solution where would always require IDs to be passed and use the following [package](https://www.npmjs.com/package/react-id-generator) to make sure we consitently generate unique IDs. Or like a comment in the above radix issue says; skip the id generation during SSR altogether.

**Comment by awilderink** [comment]
It indeed will indeed harm the synchronization between the server and the client. It's maybe indeed better to only generate the id when in the client.
