### ISSUE TITLE
Failing build

### ISSUE THREAD

**Issue by MrBamBam** [storyofams/next-boilerplate#7]
**Describe the bug**
Was playing around a little with our setup yesterday and I noticed the build is failing

**To Reproduce**
* Navigate to the project root and run `yarn build`
* It breaks on a text variant (I think we need to add at least two types to fix it)

**Expected behavior**
Build should not fail at this stage 😅 

**Screenshots or codesandbox**
![Breakage](https://user-images.githubusercontent.com/10127707/74132831-98203e80-4be7-11ea-8e73-27d1d98c3231.png)

**Comment by jescowuester** [comment]
ah yes I know why, I'll fix tomorrow
